export const ADD_MARK = 'ADD_MARK'
export const ADD_MARK_REJECT = 'ADD_MARK_REJECT'
export const EDIT_MARK = 'EDIT_MARK'
export const EDIT_MARK_REJECT = 'EDIT_MARK_REJECT'

export const ADD_CONNECTION = 'ADD_CONNECTION'